layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

repositories:
  - SPI_Serial_SRAM_23LC1024
  - PLC_Energy_Saver
  - Pygame_Projects

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: shivashankar
  medium: "@shivashankaar"
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter:
  # youtube: your_username
  # vk: your_username
