layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

repositories:
  - talkingVoltmeter
  - electronic-vault
  - verilog-libraries
  - CensorTube

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  linkedin: shivashankar
  medium: "@shivashankaar"
  stackoverflow: 9633932
  # telegram: your_username
  twitter: 9600_baud
  youtube: Shiva Shankar
  # vk: your_username

topics:
  - name: Electronics
    web_url: https://aws.amazon.com/iot/?hp=tile&tile=solutions
    image_url: /assets/img/Introduction-to-FPGAs/tinyfpga-front-back.jpg

  - name: Machine learning
    image_url: /assets/img/k_means.png

  - name: Cloud computing
    web_url: https://aws.amazon.com/iot/?hp=tile&tile=solutions
    image_url: /assets/img/aws.jpg
